services:
  database:
    image: mysql:9.1
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=db_suhi
    ports:
      - "3306:3306"
  web:
    build: .
    ports:
      - "8080:80"
