controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_login:
    path: /api/login
    controller: 'App\Controller\UserController::login'
    methods: ['POST']
user_registration:
    path: /api/registration
    controller: 'App\Controller\RegistrationController::register'
api_login_check:
    path: /api/login_check
get_product:
    path: /api/get_product
    controller: 'App\Controller\ProductController::getProduct'
get_products:
    path: /api/get_products
