controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_login:
    path: /api/login
    controller: 'App\Controller\UserController::login'
    methods: ['POST']
user_registration:
    path: /api/registration
    controller: 'App\Controller\RegistrationController::register'
api_login_check:
    path: /api/login_check
get_product:
    path: /api/get_product
    controller: 'App\Controller\ProductController::getProduct'
    methods: ['GET']
get_products:
    path: /api/get_products
    controller: 'App\Controller\ProductController::getProducts'
    methods: ['GET']
product_search:
    path: /api/product_search
    controller: 'App\Controller\SearchController::productSearch'
    methods: [ 'GET' ]
add_review:
    path: /api/user/review_add
    controller: 'App\Controller\ReviewController::addReview'
    methods: [ 'POST' ]
get_user_data:
    path: /api/user/get_user_data
    controller: 'App\Controller\ProductController::getUserData'
    methods: [ 'POST' ]
update_user_profile_picture:
    path: /api/user/update_profile_picture
    controller: 'App\Controller\UserController::updateProfilePicture'
    methods: [ 'POST' ]
update_user_data:
    path: /api/user/update_user_data
    controller: 'App\Controller\UserController::updateUserData'
    methods: [ 'POST' ]
product_filter:
    path: /api/filter
    controller: 'App\Controller\FilterController::productFilter'
    methods: [ 'POST' ]
username_check:
    path: /api/username_check
    controller: 'App\Controller\RegistrationController::usernameCheck'
    methods: [ 'POST' ]
email_check:
    path: /api/email_check
    controller: 'App\Controller\RegistrationController::emailCheck'
    methods: [ 'POST' ]
checkout:
    path: /api/checkout
    controller: 'App\Controller\CheckoutController::checkout'
    methods: [ 'POST' ]
admin_add_product:
    path: /api/admin/add_product
    controller: 'App\Controller\CheckoutController::addProduct'
    methods: [ 'POST' ]
admin_update_review:
    path: /api/admin/update_review
    controller: 'App\Controller\CheckoutController::updateReviewAdmin'
    methods: [ 'POST' ]
admin_add_review:
    path: /api/admin/add_review
    controller: 'App\Controller\CheckoutController::addReviewAdmin'
    methods: [ 'POST' ]
