controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
user_login:
    path: /api/login
    controller: 'App\Controller\UserController::login'
    methods: ['POST']
